### ISSUE TITLE
.gitignore の修正以前に生えたブランチはまだゴミだらけ

### ISSUE THREAD

**Issue by piddy-shz** [GreenTeaProgrammers/TasQuest#13]
今すぐマージするわけではないやつらなので、今後またゴミだらけにならないようにする必要がありそうです

**Comment by KinjiKawaguchi** [comment]
developにマージするときにDevelopにある削除変更ログと結合されるのでおそらく大丈夫かと、、、

コンフリクトが怖い

**Comment by KinjiKawaguchi** [comment]
これは問題なさそうなので閉じます。
#12
